name: ZombieSiege
main: zombiesiege.ZombieSiege
version: 1.0
author: allenliu
commands:
    start:
        description: Start a new game
        usage: /<command>
    end:
        description: End a game
        usage: /<command>
    stats:
        description: View game statistics
        usage: /<command>      
    debug:
        description: For debugging only
        usage: /<command>  